server:
  port: 8090
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/biology?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
mybatis-plus:
  mapper-locations: classpath:mapperxml/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
DeepSeek:
  url: "https://api.deepseek.com/chat/completions"
  model: "deepseek-reasoner"
  apiKey: "sk-674fa5a88e6d4783b98f972e77c7e10d"